spring.application.name=HeathApplication

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

azure.openai.endpoint=https://pradh-mg1v3yum-francecentral.cognitiveservices.azure.com
azure.openai.key=8ZzZ579K1leZMPJJSZxNMTSLrKDoWYNkCOzp2Uj0EzAkpdCcgdaXJQQJ99BIAC5T7U2XJ3w3AAAAACOGjsoM
azure.openai.deployment=gpt-health